- name: Remove Old Configuration if exist
  ansible.builtin.lineinfile:
    path: /etc/security/pwquality.conf
    state: absent
    regexp: '^minlen'

- name: Remove Old Configuration if exist
  ansible.builtin.lineinfile:
    path: /etc/security/pwquality.conf
    state: absent
    regexp: '^dcredit'

- name: Remove Old Configuration if exist
  ansible.builtin.lineinfile:
    path: /etc/security/pwquality.conf
    state: absent
    regexp: '^ucredit'

- name: Remove Old Configuration if exist
  ansible.builtin.lineinfile:
    path: /etc/security/pwquality.conf
    state: absent
    regexp: '^lcredit'

- name: Remove Old Configuration if exist
  ansible.builtin.lineinfile:
    path: /etc/security/pwquality.conf
    state: absent
    regexp: '^minclass'

- name: Insert new Configuration of Password Complexity settings REDHAT
  blockinfile:
    path: /etc/security/pwquality.conf
    block: |
      ###Ajouter pour complexité Password : 14 caractères dont au minimum 2 Chiffres + 3 Majuscule + 3 Minuscule et le reste du type  Majuscule, Minuscule, Chiffre ou Caractère spécial
      minlen = 14
      dcredit = -2
      ucredit = -3
      lcredit = -3
      minclass = 3
